### ISSUE TITLE
每一道题使用不同的URL

### ISSUE THREAD

**Issue by boomzero** [langningchen/OJ#1]
rt

**Comment by langningchen** [comment]
这个对于纯 C++ 写的服务器有点难

**Comment by langningchen** [comment]
可以考虑

**Comment by langningchen** [comment]
@boomzero 好了

**Comment by langningchen** [comment]
985c8acd3d0069242ceddbf17fc660ff20dd4d00

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/OJ/assets/81672884/ae5aafea-d188-4154-a9c8-c1d85239c191)

**Comment by langningchen** [comment]
其他的和这个一样的道理

**Comment by langningchen** [comment]
这样直接 F5 也不会出现样式不对的情况了
